failed step

diff --git a/.github/workflows/01-firstjob-action.yaml b/.github/workflows/01-firstjob-action.yaml
--- a/.github/workflows/01-firstjob-action.yaml
+++ b/.github/workflows/01-firstjob-action.yaml
@@ -6,3 +6,11 @@ jobs:
     steps:
       - name: Say Hello
         run: echo "hello world"
+
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: failed step
+        run: |
+          echo "failing now"
+            exit 1
